package net.rafaelaznar.bean;
// Generated Jan 21, 2014 12:40:47 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

    private Integer id = 0; //ojo, poner valores por defecto
    private String codigo;
    private String descripcion;
    private BigDecimal precio;
    private Integer id_tipoproducto; //modificado por rafa antes: idTipoproducto

    public Producto() {
    }

    public Producto(String codigo, String descripcion, BigDecimal precio, Integer idTipoproducto) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.precio = precio;
        this.id_tipoproducto = idTipoproducto;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    public Integer getIdTipoproducto() {
        return this.id_tipoproducto;
    }

    public void setIdTipoproducto(Integer idTipoproducto) {
        this.id_tipoproducto = idTipoproducto;
    }

}
