package net.rafaelaznar.bean;
// Generated Jan 21, 2014 12:40:47 PM by Hibernate Tools 3.6.0

/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto implements java.io.Serializable {

    private Integer id = 0;
    private String descripcion;

    public Tipoproducto() {
    }

    public Tipoproducto(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
