package net.rafaelaznar.bean;
// Generated Jan 21, 2014 12:40:47 PM by Hibernate Tools 3.6.0

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer id = 0; //ojo, poner valores por defecto
    private String nombre;
    private String email;
    private String login;
    private String password;

    public Usuario() {
    }

    public Usuario(String nombre, String email, String login, String password) {
        this.nombre = nombre;
        this.email = email;
        this.login = login;
        this.password = password;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
